### ISSUE TITLE
Not working :c

### ISSUE THREAD

**Issue by JustinOsu** [Wieku/danser#7] opened 2018-08-24 19:38 UTC
PS C:\Users\Justin\Desktop\Danser> .\danser-0.1.2b.exe -title="IMAGE -MATERIAL-"
2018/08/24 21:36:56 Checking database...
2018/08/24 21:36:58 Imported 0 new beatmaps.
2018/08/24 21:36:58 Found 6770 cached beatmaps. Loading...
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/wieku/danser/beatmap.(*BeatMap).LoadTimingPoints(0xc0443ae000)
        C:/Users/Wieku/go/src/github.com/wieku/danser/beatmap/beatmap.go:67 +0x5cd
github.com/wieku/danser/database.loadBeatmaps(0xc042a24000, 0x1a72, 0x1c00)
        C:/Users/Wieku/go/src/github.com/wieku/danser/database/manager.go:170 +0x626
github.com/wieku/danser/database.LoadBeatmaps(0x0, 0x0, 0x0)
        C:/Users/Wieku/go/src/github.com/wieku/danser/database/manager.go:103 +0x3fb
main.run.func1()
        C:/Users/Wieku/go/src/github.com/Wieku/danser/main.go:59 +0x35f
github.com/faiface/mainthread.Call.func1()
        C:/Users/Wieku/go/src/github.com/faiface/mainthread/mainthread.go:63 +0x39
github.com/faiface/mainthread.Run(0x6c2aa8)
        C:/Users/Wieku/go/src/github.com/faiface/mainthread/mainthread.go:44 +0xc5
main.main()
        C:/Users/Wieku/go/src/github.com/Wieku/danser/main.go:193 +0x34
PS C:\Users\Justin\Desktop\Danser>

**Comment by Wieku** [comment] 2018-08-24 19:47
Duplicate of #5

**Comment by Wieku** [comment] 2018-08-24 19:47
Still i would love to see that .db file

**Comment by JustinOsu** [comment] 2018-08-24 19:47
Simple fix: just delete the danser.db...

**Comment by JustinOsu** [comment] 2018-08-24 19:50
https://s.enjuu.click/danser.db

**Closed** 2018-08-25 04:50 UTC
